" Turn on syntax highlighting
syntax on

" Show line numbers
set number
" set nonumber

" https://github.com/w0ong/vim-hybrid
colorscheme hybrid
set background=dark
let g:hybrid_custom_term_colors = 1

" Pathogen 
execute pathogen#infect()
filetype plugin indent on

" Rust
let g:rust_clip_command = 'xclip -selection clipboard'
"  let g:rust_clip_command = 'pbcopy'

" Escape
imap jj <esc>

" Surround
let b:surround_indent = 0

" netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3
" 1 - open files in a new horizontal split
" 2 - open files in a new vertical split
" 3 - open files in a new tab
" 4 - open in previous window
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 20
" Toggle Vexplore with Ctrl-E
function! ToggleVExplorer()
  if exists("t:expl_buf_num")
      let expl_win_num = bufwinnr(t:expl_buf_num)
      if expl_win_num != -1
          let cur_win_nr = winnr()
          exec expl_win_num . 'wincmd w'
          close
          exec cur_win_nr . 'wincmd w'
          unlet t:expl_buf_num
      else
          unlet t:expl_buf_num
      endif
  else
      exec '1wincmd w'
      Vexplore
      let t:expl_buf_num = bufnr("%")
  endif
endfunction
map <silent> <C-E> :call ToggleVExplorer()<CR>
" Change dir to the current buffer when opening files
set autochdir

filetype plugin indent on
" show existing tab with 2 spaces width
set tabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2
" On pressing tab, insert 2 spaces
set expandtab

" Spelling
set spell
