source $HOME/.ideavimrc

" Turn on syntax highlighting
syntax on

" Show line numbers
set number

" https://github.com/w0ong/vim-hybrid
colorscheme hybrid
set background=dark
let g:hybrid_custom_term_colors = 1

" Pathogen 
execute pathogen#infect()
filetype plugin indent on

" show existing tab with 2 spaces width
set tabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2 " On pressing tab, insert 2 spaces
set expandtab

" Rust
let g:rustfmt_autosave = 1
if system("uname") == "Linux"
  let g:rust_clip_command = 'xclip -selection clipboard'
endif
if system("uname") == "Darwin"
  let g:rust_clip_command = 'pbcopy'
endif

" Surround
let b:surround_indent = 0

" NerdTree
map <C-E> :NERDTreeToggle<CR>
map <C-L> :NERDTreeFind<CR>

" Close window if only NT is open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Spelling
set nospell
