" Turn on syntax highlighting
syntax on

" Show line numbers
set number
" set nonumber

" https://github.com/w0ong/vim-hybrid
colorscheme hybrid
set background=dark
let g:hybrid_custom_term_colors = 1

" Pathogen 
execute pathogen#infect()
filetype plugin indent on

" Rust
let g:rust_clip_command = 'xclip -selection clipboard'
"  let g:rust_clip_command = 'pbcopy'

" Escape
imap jj <esc>

" Surround
let b:surround_indent = 0

" netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3
" 1 - open files in a new horizontal split
" 2 - open files in a new vertical split
" 3 - open files in a new tab
" 4 - open in previous window
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 20
augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * :Vexplore
augroup END
